version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.10

    working_directory: ~/repo/lesson-3-independent-releases/exercises/travis_ci/

    steps:
      - checkout:
            path: ~/repo
            
      - run: npm install

      - run: docker --version
      - run: docker build -t simple-node .
      - run: docker tag simple-node majiduddev/debug-me:latest
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push majiduddev/debug-me