version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.10

    working_directory: ~/repo/lesson-3-independent-releases/exercises/travis_ci/

    steps:
      - checkout:
            path: ~/repo
            
      - run: npm install

      - run: npm test